### ISSUE TITLE
Add support for regression

### ISSUE THREAD

**Issue by snicoll** [mbhave/release-notes-generator#6]
We have a regression type that we use to indicate that a behaviour has been broken. This should probably show up first and foremost considering this may have impact on users.

The release notes do not contain them at the moment.

**Comment by mbhave** [comment]
good catch.

**Comment by mbhave** [comment]
I can't think of a good emoji for that 🤔

**Comment by snicoll** [comment]
🚨

**Comment by snicoll** [comment]
To avoid creating too much sections, I think it's fine to include them in the "bug" section.
